// <auto-generated />
using CIDM3312_Final.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIDM3312_Final.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220501203643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("CIDM3312_Final.Models.Hunt", b =>
                {
                    b.Property<int>("HuntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("H1Dmg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("H1Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("H2Dmg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("H2Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("H3Dmg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("H3Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("H4Dmg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("H4Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("Monster")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("HuntID");

                    b.ToTable("Hunts");
                });

            modelBuilder.Entity("CIDM3312_Final.Models.Hunter", b =>
                {
                    b.Property<int>("HunterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("TDmg")
                        .HasColumnType("INTEGER");

                    b.HasKey("HunterID");

                    b.ToTable("Hunters");
                });

            modelBuilder.Entity("CIDM3312_Final.Models.HuntersHunt", b =>
                {
                    b.Property<int>("HunterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HuntID")
                        .HasColumnType("INTEGER");

                    b.HasKey("HunterID", "HuntID");

                    b.HasIndex("HuntID");

                    b.ToTable("HuntersHunts");
                });

            modelBuilder.Entity("CIDM3312_Final.Models.HuntersHunt", b =>
                {
                    b.HasOne("CIDM3312_Final.Models.Hunt", "Hunt")
                        .WithMany("HuntersHunt")
                        .HasForeignKey("HuntID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIDM3312_Final.Models.Hunter", "Hunter")
                        .WithMany("HuntersHunt")
                        .HasForeignKey("HunterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
